{
 "title": "IM K8s cluster portal",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" },
   { "name": "ds", "query": "datasource" },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "query": "label_values(node_boot_time_seconds{job=\"node-exporter\"}, instance)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "All Pods Status",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{namespace=~\"$namespace\"} > 0",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Firing Alerts",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\"})"
    }
   ]
  },
  {
   "title": "Currently running Jenkins builds",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_labels{namespace=~\"$namespace\", label_jenkins=\"slave\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Recent Alerts",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 11, "x": 11, "y": 4 },
   "targets": [
    { "expr": "ALERTS" }
   ]
  },
  {
   "title": "Recent jenkins job pods",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "kube_pod_labels{namespace=~\"$namespace\", label_jenkins=\"slave\", job=\"kube-state-metrics\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods statuses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 11, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Pod count" }
   ],
   "targets": [
    {
     "expr": "sum by (phase)(kube_pod_status_phase{namespace=~\"$namespace\", job=\"kube-state-metrics\"})",
     "legendFormat": "{{phase}}"
    }
   ]
  }
 ]
}