apiVersion: v1
kind: ConfigMap
metadata:
  name: zal
data:
  sender-config.yml: |-
    # Resolver name to zabbix host mapping
    # web is Alertmanager's resolver name
    # and the mapping is Zabbix host name.
    zal: {{ .Values.cluster_name }}