apiVersion: v1
kind: Service
metadata:
  name: zal
  labels:
    name: zal
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/scrape: "true"
spec:
  ports:
  - port: 9095
    protocol: TCP
    targetPort: 9095
  selector:
    k8s-app: zal

